name: flutter_catalog
description: A new Flutter project.

# *Note*: when version change, remember to also update constants.dar
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_floatactionbuttons: '0.1.0'
  async: '^2.2.0'
  backdrop: '0.1.8'
  cached_network_image: '2.0.0-rc.1'
  charts_flutter: '0.8.1'
  cloud_firestore: '0.12.10+2'
  english_words: '3.1.5'
  firebase_analytics: '3.0.3'
  firebase_auth: '0.14.0+5'
  firebase_core: '0.4.0+9'
  firebase_database: '3.0.7'
  firebase_ml_vision: '0.9.3'
  firebase_storage: '3.0.6'
  flutter_bloc: '0.18.3'
  flutter_gallery_assets: '0.1.9+2'
  flutter_markdown: '0.2.0'
  flutter_webview_plugin: '0.3.5'
  fluttertoast: '3.1.0'
  google_sign_in: '4.0.2'
  hive_flutter: '0.2.1'
  hive: '1.1.1'
  image_picker: '0.6.0+11'
  local_auth: '0.5.2+4'
  package_info: '0.4.0+4'
  path_provider: '1.1.0'
  path: '^1.6.2'
  provider: '3.0.0+1'
  scoped_model: '1.0.1'
  sembast: '2.0.1'
  shared_preferences: ' 0.5.3+1'
  sqflite: '1.1.6+3'
  transparent_image: '1.0.0'
  url_launcher: '5.2.7'
  widget_with_codeview: '1.0.3'

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: '0.5.2'
  build_runner: '1.7.1'

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  # Note: when new assets are added, have to run `flutter clean` to see 
  # changes take effect.
  assets:
    # *Tip*: keep the slash at the end of folder path adds all files to 
    # assets. Note: this doesn't work with subfolders. 
    # c.f. https://github.com/flutter/flutter/issues/4890#issuecomment-407327749
    - lib/routes/
    - res/images/
    - packages/flutter_gallery_assets/animated_images/animated_flutter_stickers.webp
  
  fonts:
    - family: monospace
      fonts:
        - asset: res/DroidSansMono.ttf